---
# tasks file for deploy_apache_web

- name: Install Apache Web Server and other web components
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - "apache2"
    - "libapache2-mod-wsgi-py3"
    - "python3-pip"
    - "python3-virtualenv"

- name: Start Web Server service
  service: name=apache2 state=started enabled=true

- name: Generate page of apache server
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0755

